select * from customer_shopping limit 20;

--Q1. What is the total revenue generated by male vs. female customer?

SELECT gender, SUM(purchase_amount) as Revenue 
from customer_shopping
group by gender;

--Q2. which customer used a discount but still spend more than the average purchase amount?
select customer_id, purchase_amount
from customer_shopping
where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_shopping)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer_shopping
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. compare the average purchase amounts between standard and express shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer_shopping
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscriber.
select subscription_status,
COUNT(customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer_shopping
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer_shopping
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from customer_shopping
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. what are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer_shopping
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9 are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases > 5
group by subscription_status

--Q10. what is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer_shopping
group by age_group
order by total_revenue desc;
